Models/Comentario.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Oblitas_Tafur_Eliana_T1.Models
{
    public class Comentario
    {
        public int Id { get; set; }
        public String Opinion { get; set; }
        public DateTime FechaComentario { get; set; }
        public int IdPost { get; set; }
    }
}

Models/ErrorViewModel.cs
using System;

namespace Oblitas_Tafur_Eliana_T1.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Models/Examen_T1_Contexto.cs
using Microsoft.EntityFrameworkCore;
using Oblitas_Tafur_Eliana_T1.Models.Mapeo;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Oblitas_Tafur_Eliana_T1.Models
{

    public class Examen_T1_Contexto : DbContext
    {
        public DbSet<Post_clase> Posts { get; set; }
        public DbSet<Comentario> Comentarios { get; set; }
        public Examen_T1_Contexto(DbContextOptions<Examen_T1_Contexto> options)
            : base(options) { }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new Post_Mapeo());
            modelBuilder.ApplyConfiguration(new Comentario_Map());
        }
    }

}

Models/Mapeo/Comentario_Map.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Oblitas_Tafur_Eliana_T1.Models.Mapeo
{
    public class Comentario_Map : IEntityTypeConfiguration<Comentario>
    {
        public void Configure(EntityTypeBuilder<Comentario> builder)
        {
            builder.ToTable("Comentario");
            builder.HasKey(o => o.Id);
        }
    }
}

Models/Mapeo/Post_Mapeo.cs
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Oblitas_Tafur_Eliana_T1.Models.Mapeo
{

    public class Post_Mapeo :IEntityTypeConfiguration<Post_clase>
    {
 

        public void Configure(EntityTypeBuilder<Post_clase> builder)
        {
            builder.ToTable("Post_clase");
            builder.HasKey(o => o.Id);

            builder.HasMany(o => o.Comentario).
                WithOne().
                HasForeignKey(o => o.IdPost);
        }
    }
}

Models/Post_clase.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Oblitas_Tafur_Eliana_T1.Models
{
    public class Post_clase
    {
        public int Id { get; set; }
        public String Nombre { get; set; }
        public String Autor { get; set; }

        public String Contenido { get; set; }
        public DateTime Fecha_Creacion { get; set; }
        public List<Comentario> Comentario { get; set; }
    }
}

Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Oblitas_Tafur_Eliana_T1.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace Oblitas_Tafur_Eliana_T1.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Controllers/PostController.cs
using Microsoft.AspNetCore.Mvc;
using Oblitas_Tafur_Eliana_T1.Models;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Oblitas_Tafur_Eliana_T1.Controllers
{
    public class PostController : Controller
    {
        private readonly Examen_T1_Contexto context;

        public PostController(Examen_T1_Contexto context)
        {
            this.context = context;
        }
        [HttpGet]
        public ActionResult Index()
        {
            var post = context.Posts.OrderByDescending(o => o.Fecha_Creacion).ToList();
            return View(post);
        }
        [HttpPost]
        public ActionResult Registrar(Post_clase post)
        {
            post.Fecha_Creacion = DateTime.Now;
            context.Posts.Add(post);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult Registrar()
        {
            return View("Registrar", new Post_clase());
        }
        [HttpGet]
        public ActionResult Detalle(int id)
        {
            var post = context.Posts.Where(o => o.Id == id).FirstOrDefault();
            ViewBag.Comentario = context.Comentarios.
                Where(o => o.IdPost == id).
                OrderByDescending(o => o.FechaComentario).
                ToList();
            return View(post);
        }
        [HttpPost]
        public ActionResult RegistrarComentario(Comentario comentario)
        {
            comentario.FechaComentario = DateTime.Now;
            context.Add(comentario);
            context.SaveChanges();
            return RedirectToAction("Index");
        }
        [HttpGet]
        public ActionResult RegistrarComentario(int id)
        {
            ViewBag.Id = id;
            return View("RegistrarComentario", new Comentario());
        }
    }
}

Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Views/Post/Detalle.cshtml
@{ 
    var post = (Post_clase)Model;
    var comentario = (List<Comentario>)ViewBag.Comentario;
}
<div>
    <h3>@post.Nombre</h3>
    <div>
        <p>@post.Autor</p>
        <p>@post.Fecha_Creacion</p>
        <div>
            <p><strong>Contenido</strong>@post.Contenido</p>
        </div>
    </div>
</div>
<div>
    <h3>COMENTARIOS</h3>

    <a href="/Post/RegistrarComentario?id=@post.Id">Nuevo Comentario</a>
    <div>
        @foreach(var item in comentario)
            {
                <p>@item.Opinion</p>
                <p>Fecha creacion: @item.FechaComentario</p>
            }
    </div>
</div>

Views/Post/Index.cshtml
@{ 
    var post = (List<Post_clase>)Model;
}
<h1>Post T1_DIARS_Eliana</h1>

<a href="/Post/registrar">Crear Blog Post</a>
<br />
<table class="table"> 
    <thead>
        <tr>
            <th>Nombre</th>
            <th>Autor</th>
            <th>Fecha de Creacion</th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in post)
        {
        <tr>
            <td>@item.Nombre</td>
            <td>@item.Autor</td>
            <td>@item.Fecha_Creacion</td>
            <td><a href="/Post/Detalle?id=@item.Id">Detalle</a></td>
        </tr>
        }

    </tbody>
</table>

Views/Post/Registrar.cshtml
@{ 
    var post = (Post_clase)Model;
}
<h1>registrar Post</h1>

    <div class="row">
        <div class="col-6">
            <form action="/Post/Registrar" method="post">
                <div class="form-group">
                    <label>Nombre</label>
                    <input class="form-control" name="nombre" />
                </div>
                <div class="form-group">
                    <label>Autor</label>
                    <input class="form-control" name="autor" />
                </div>
                <div class="form-group">
                    <label>Contenido</label>
                    <input class="form-control" name="contenido" />
                </div>
                <button class="btn btn-primary">Guardar</button>
            </form>
        </div>
    </div>

Views/Post/RegistrarComentario.cshtml
<div>
    <form action="/Post/RegistrarComentario" method="post">
        <input type="hidden" name="IdPost" value="@ViewBag.Id" />
        <div>
            <textarea class="form-control" name="Opinion" placeholder="Ingresar nuevo comentario"></textarea>
        </div>
        <button class="btn btn-primary">Comentar</button>
    </form>
</div>

Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Oblitas_Tafur_Eliana_T1</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Oblitas_Tafur_Eliana_T1</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Post" asp-action="Index">Post</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - Oblitas_Tafur_Eliana_T1 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>